<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
 	<meta http-equiv="Content-Language" content="pt-Br">
	<link rel="stylesheet" type="text/css" href="<?= assets('css/stilo.css'); ?>">
	<script type="text/javascript" src=<?= assets("js/jquery-3.2.1.slim.min.js") ?> ></script>
	<script type="text/javascript" src=<?= assets("js/jquery.maskedinput.min.js") ?> ></script>  
	
	<link href="<?= assets('css/font-awesome.min.css'); ?>" rel="stylesheet" >
	<title>BÍBLIOS</title>
	<link rel="SHORTCUT ICON" href="<?= assets('img/favicon.ico')?>">
</head>
<body>
	<div class="topo">
		<div class="logo">
			<div class="esquerda">
				<img src="<?= assets('img/logo.png');?>" width="30%" alt="">
			</div>
			<div class="direita">
				<?php 
					if(isset($_SESSION['user']) && !empty($_SESSION['user'])){ ?>
						<a href="<?= url('/sair') ?>" class="fa fa-sign-out" aria-hidden="true" title="Sair"></a>
						<label> <?= $_SESSION['user'] ?></label>
				<?php } else{ ?>
					<a href="<?= url('/login') ?>" class="fa fa-sign-out" aria-hidden="true" title="Sair"> Fazer Login</a>
				<?php }	?> 
			</div>
		</div>
	</div>
	<div class="nav-esquerda">
		<div class="menu">

			<ul>
				<small>menu</small >
				<?php if(isset($_SESSION['user']) && $_SESSION['perfil'] == 1){ ?>
					<a href="<?= url('/') ?>"><li>
						<i class="fa fa-home" aria-hidden="true"></i>
						Início</li>
					</a>
					<a href="<?= url('/acervo') ?>"><li>
						<i class="fa fa-book" aria-hidden="true"></i>
						Acervo</li>
					</a>
					<a href="<?= url('/funcionario') ?>"><li>
							<i class="fa fa-user" aria-hidden="true"></i>
							Funcionarios</li>
					</a>
					<a href="<?= url('/emprestimo') ?>"><li>
						<i class="fa fa-exchange" aria-hidden="true"></i>
						Emprestimo</li>
					</a>
				<?php } else { ?>
					<a href="<?= url('/acervo') ?>"><li>
						<i class="fa fa-book" aria-hidden="true"></i>
						Acervo</li>
					</a>
					<?php if(isset($_SESSION['user'])){ ?>
					<a href="<?= url('/emprestimo/minhalista') ?>"><li>
						<i class="fa fa-exchange" aria-hidden="true"></i>
						Meus Emprestimos</li>
					</a>
					
				<?php }} ?>
			</ul>
		</div>
	</div>
	<div class="conteudo">
		<!-- <h3>CADASTRAR</h3> -->
			<div class="caixa-dir">
				<div class="body">
                    <?= $this->yieldView(); ?>
				</div>
			</div>
	</div>
  <script type="text/javascript" src="<?= assets("js/mascaras.js") ?>"></script>	
</body>
</html>
