<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="../css/login.css">
  <title>login</title>
</head>
<body>
  <form class="form-login" action="inicio.html" method="post">
    <div>
      <h2>BIBLIOS</h2>
    </div>
    <div class="login">
      <div class="login-info">
        <input placeholder="Usuario" type="text" name="usuario" value="">
      </div>
      <div class="login-info">
        <input placeholder="Senha" type="password" name="senha" value="">
      </div>
      <button type="submit">entrar</button>
    </div>
  </form>
</body>
</html>
