<div class="cabecalho">
    <label>
        <i class="fa fa-exchange" aria-hidden="true"></i>
            Emprestimo / Confirmar Emprestimo
    </label>
</div>
<div class="titulo-pg">
    <label style="margin-left:20px;">Estamos quase lá, informe o CPF do funcionário para realizat o emprestimo.</label>
</div>
<br>
<form action="<?= url('/emprestimo/confirmar')?>" method="POST" class="form">
    <input type="text" name="strcpf" value="" placeholder="CPF" class="ano">
    
    <button class="but-war" style="font-size:16px;width:200px;margin-left:7px;">Confirmar Emprestimo</button>
</form>