
<div class="cabecalho">
	<label><i class="fa fa-user" aria-hidden="true"></i> Funcionarios</label>
	<div class="opcao">
			<a class="but-suc" href="<?= url('/funcionario/novo') ?>"><i class="fa fa-plus" aria-hidden="true"></i>
					Cadastrar</a>
	</div>
	<br><br>
	<hr>

	<div class="barra-pesquisa">
		<!-- <form action="inicio.html">
			<input class="campo-pesquisa" type="text" placeholder="faça sua busca">
			<button class="but-pes" type="submit" style="width:90px;">
				<i class="fa fa-search" aria-hidden="true"></i>
				Buscar</button>
		</form> -->
	</div>
</div>
<!-- <div class="titulo-pg">
	<label>Lista de Exemplares</label>
</div> -->

<table>
	<thead>
		<tr>
			<th>#</th>
			<th>ID</th>
			<th>Cargo</th>
			<th>Nome</th>
			<th>Acão</th>
		</tr>
	</thead>
	<tbody>
	<?php
	if(empty($this->lista)){
		echo '<tr> <td colspan="6" style="background-color: #ccc;"> Não Funcionarios Cadastrados</td> </tr>';
	} else {
	foreach ($this->lista as $key => $funcionario) { ?>
		<tr style="<?php if($key%2 == 0) echo 'background-color: #dbe4f3;' ?>">
			<td><?= ++$key ?></td>
			<td><?= $funcionario['idfuncionario'] ?></td>
			<td><?= $funcionario['strnometipo'] ?></td>
			<td><?= $funcionario['strnomefuncionario'] ?></td>
			<td>
				<a class="but-info" href="<?= url('/funcionario/'.$funcionario['idfuncionario'].'/editar') ?>"><i class="fa fa-pencil" aria-hidden="true"></i>
					Editar</a>
				<a class="but-dan" href="<?= url('/funcionario/'.$funcionario['idfuncionario'].'/excluir') ?>"><i class="fa fa-trash" aria-hidden="true"></i>
					Excluir</a>
			</td>
		</tr>
	<?php } } ?>
	</tbody>
</table>