<div class="cabecalho">

    
    <label>
        <i class="fa fa-book" aria-hidden="true"></i>
        Acervo / Cadastro
    </label>
</div>
<div class="titulo-pg">
    <label style="margin-left:20px;">Faça aqui o cadastro do seus exemplares.</label>
</div>
<br>
<form action="<?= url('/acervo/novo')?>" method="POST" class="form">
    <!-- <span>Titulo do Livro:*</span><br> -->
    <input type="text" value="<?= isset($this->livro['strnomeexemplar'])? $this->livro['strnomeexemplar'] : ''; ?>" name="titulo" placeholder="Titulo" class="autor" required>
    <select class="area" riquired="riquired" name="area" id="" required>
        <!-- <option value="">SELECIONE UMA AREA</option> -->
        <option value="">SELECIONE UMA AREA</option>
            <?php foreach($this->areas as $area) { ?>
        <option <?php if(isset($this->livro['idexemplararea']) && ($this->livro['idexemplararea'] == $area['idexemplararea'])) echo 'selected="selected"'; ?> value="<?= $area['idexemplararea']; ?>" ><?= $area['strnomearea']; ?></option>
            <?php };?>
    </select>
    <input type="text" value="<?= isset($this->livro['strautor'])? $this->livro['strautor'] : ''; ?>" name="autor" placeholder="Autor" class="autor" required>
    <input type="text" value="<?= isset($this->livro['dtaano'])? $this->livro['dtaano'] : ''; ?>" name="ano" placeholder="Ano" class="ano" required>
    <input type="text" value="<?= isset($this->livro['streditora'])? $this->livro['streditora'] : ''; ?>" name="editora" placeholder="Editora"  class="editora" required>
    <input type="<?=  isset($this->livro['strisbn']) ? 'hidden' : 'text' ?>" name="quantidade" id="" placeholder="Quantidade" class="preco">
    <input type="text" value="<?= isset($this->livro['strpreco'])? $this->livro['strpreco'] : ''; ?>" name="preco" placeholder="Preço" class="preco" required>
    <input type="number" value="<?= isset($this->livro['strisbn'])? $this->livro['strisbn'] : ''; ?>" name="strisbn" placeholder="ISBN" class="preco" required>    
    <br><br>
    <!-- <input type="hidden" value="<?= isset($this->livro['idexemplar'])? $this->livro['idexemplar'] : ''; ?>" name="id"> -->
    
    <?php if($this->livro){ ?>
    <button class="but-info" style="font-size:16px;width:90px;margin-left:7px;">Editar</button>
    <?php } else {?>
    <button class="but-suc" style="font-size:16px;width:90px;margin-left:7px;">Cadastrar</button>
    <?php } ?>
</form>